<a href="https://colab.research.google.com/github/DeepandraSingh1225/Aws-ML/blob/main/day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[0:4]) # slicing
print(arr[-1])
print(arr[:])
print(arr[0:3:2]) # start from 0 to 3 and jump 1
print(arr[::2]) # jump by one
print(arr[::-1]) # reverse

arr[3:len(arr)]
arr[-2:]

3
[1 2 3 4]
5
[1 2 3 4 5]
[1 3]
[1 3 5]
[5 4 3 2 1]


array([4, 5])

#### 2d

In [15]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr)
print()
print(arr[0:2])   # row
print()
print(arr[:,0])  # all row 0 column
print()
print(arr[0,0])

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

[1 4]

1


In [32]:
arr = np.array([[10,20] , [30,40]])
print(arr)
print()
print(arr[0,0])
print()
print(arr[1,1])
print()

print(arr[:,1])
print()
print(arr[[0,1],[1,0]])   # row 0 col 1 then row 1 col 0
print()
print(arr[[0,1] , [0,1]])
print()

[[10 20]
 [30 40]]

10

40

[20 40]

[20 30]

[10 40]



In [45]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr)
print()
print(arr[[0,1] , [2,1]])

[[1 2 3]
 [4 5 6]]

[3 5]


In [62]:
import numpy as np

arr = np.array([
    [2453,   75, 183975],
    [5795,   99, 573705],
    [4100,   36, 147600],
    [7526,   86, 647236],
    [9528,   45, 428760],
    [10788,  17, 183396]
])

print(arr)
print()
print(arr[4:,1])
print()
print(arr[0,:2])
print()
print(arr[[0,1] ,[2,1]])
print()
print(arr[[2,3] , [0,2]])
print()
print(arr[[2, 3, 3, 3], [0, 0, 1, 2]])
print()


[[  2453     75 183975]
 [  5795     99 573705]
 [  4100     36 147600]
 [  7526     86 647236]
 [  9528     45 428760]
 [ 10788     17 183396]]

[45 17]

[2453   75]

[183975     99]

[  4100 647236]

[  4100   7526     86 647236]


#### 3d

In [71]:
# 3d  in this [block , row , col]
import numpy as np
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
    ])
print(arr.ndim) # 3d
print(arr)
# print(arr[0])
# print(arr[0,0])
# print(arr[0,0,0])

print()
print(arr[:,0])  # all block row 0
print()
print(arr[:,:,0])  # all block all row  col 0


3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[1 2]
 [5 6]]

[[1 3]
 [5 7]]


#### looping with numpy

In [73]:
arr = np.array([10,20,30,40])
print(arr)

for i in arr:
  print(i)

[10 20 30 40]
10
20
30
40


In [80]:
arr = np.array([[1,2] , [3,4] , [5,6]])
print(arr)
print()

for i in arr:
  for j in i:
    print(j)

[[1 2]
 [3 4]
 [5 6]]

1
2
3
4
5
6
