<a href="https://colab.research.google.com/github/DeepandraSingh1225/Aws-ML/blob/main/day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Filter

In [11]:
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr > 20]
arr_f

array([ 90, 200])

In [9]:
arr = np.array([10,20,11,12,13,14,15,16,29,3,4,90,200])
arr_f = arr[(arr < 20) & (arr>10)]
arr_f

array([11, 12, 13, 14, 15, 16])

#### Where

In [2]:
arr = np.array([10,20,30,40])
print(np.where(arr > 30 , 'true' , 'false'))

print(np.where(arr > 20 , arr*2 , arr))

['false' 'false' 'false' 'true']
[10 20 60 80]


#### Fancy indexing

In [12]:
arr = np.array([10,20,3,4,90,200])
print(arr)
arr_f = arr[[0,2]]
print(arr_f)

[ 10  20   3   4  90 200]
[10  3]
