<a href="https://colab.research.google.com/github/DeepandraSingh1225/Aws-ML/blob/main/day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Filter

In [ ]:
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr > 20]
arr_f

array([ 90, 200])

#### Where

In [ ]:
arr = np.array([10,20,11,12,13,14,15,16,29,3,4,90,200])
arr_f = arr[(arr < 20) & (arr>10)]
arr_f

array([11, 12, 13, 14, 15, 16])

In [45]:
arr = np.array([10,20,30,40])
print(np.where(arr > 30 , 'true' , 'false'))

print(np.where(arr > 20 , arr*2 , arr))

['false' 'false' 'false' 'true']
[10 20 60 80]


In [46]:
arr = np.array([10,20,11,12,13,14,15,16,29,3,4,90,200])
arr_f = np.where((arr < 20) & (arr>10), arr*2 , arr+2)
arr_f

array([ 12,  22,  22,  24,  26,  28,  30,  32,  31,   5,   6,  92, 202])

#### Fancy indexing

In [ ]:
arr = np.array([10,20,3,4,90,200])
print(arr)
arr_f = arr[[0,2]]
print(arr_f)

[ 10  20   3   4  90 200]
[10  3]


#### Adding and Removing Data

- np.concatenate((arr1,arr2))
- np.vstack((original,new_row)) add new row
- np.hstack((original,new_col)) add new col
- np.delete(arr,index_no) delete element by index number

#### Concatinate

In [48]:
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

# concatenate
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)
print()

# concatenate using 2d axi
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2))
print(arr1_arr2)
print()

# concatenate using 2d axis
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2) , axis = 1)
print(arr1_arr2)
print()



[10 20 30  1  2  3]

[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]

[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]



#### vstack and hstack

In [53]:
# vstack -> vertically join | row wise

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.vstack((arr1,arr2))
print(result)
print()

# hstack -> horizontally join | column wise

arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.hstack((arr1,arr2))
print(result)
print()

# 2d vstack and hstack

arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[1,2,3],[4,5,6]])
result = np.vstack((arr1,arr2))
print(result)
print()

result = np.hstack((arr1,arr2))
print(result)

[[1 2 3]
 [4 5 6]]

[10 20 30 40 50 60]

[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]

[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


#### Mean , Mode , Median
- Mean = Avg
- Mode = most occuring ele
- Median = middle ele of array after sorting

#### Median
#### 1 Given numbers: 2, 3, 1, 9, 7

- Arrange in ascending order:
- 1, 2, 3, 7, 9
- The middle value is 3

- Median = 3 ✅

#### 2 For the numbers 2, 3, 1, 7:

- Sort them: 1, 2, 3, 7

- There are 4 numbers (an even count), so the median is the average of the two middle numbers:

- 2+3/2

- Median = 2.5 ✅

In [56]:
a = np.array([1,2,3,4,5,6,7,8,9])

# one way
print('Mean : ' , np.mean(arr))
print('Median : ' , np.median(arr))
print('Min : ' , np.min(arr))
print('Max : ' , np.max(arr))
print(np.argmax(arr))
print(np.argmin(arr))


#another
print('Mean : ' , arr.mean())
print('Median : ' , np.median(arr))
print('Min : ' , arr.min())
print('Max : ' , arr.max())
print(arr.argmax())
print(arr.argmin())


Mean :  33.61538461538461
Median :  14.0
Min :  3
Max :  200
Mode :  12
Mode :  9


#### Statistical Functions

 - np.sum(a) -> Sum of all elements

 - np.mean(a) -> Average = Sum of elements / Number of elements

 - np.median(a) -> Middle value after sorting

 - np.min(a) -> Smallest value in array

 - np.max(a) -> Largest value in array

 - np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length

 - np.std(a) -> Standard Deviation = √Variance -> Measures spread of data

 - np.prod(a) -> Multiplication of all elements

 - np.cumsum(a) -> Cumulative (running) sum

 - np.cumprod(a) -> Cumulative (running) product

 - np.argmin(a) -> Index position of minimum value

 - np.argmax(a) -> Index position of maximum value

 - np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)

 - np.unique(a) -> Returns unique values only -> Removes duplicates

 - np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median

 - np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%

 - np.ptp(a) -> Range = Max - Min

 - np.any(a) -> True if at least one value is True

In [58]:
a = np.array([1,2,3,4,5,6,7,8,9])


print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))
print("Variance:", np.var(a))
print("Standard Deviation:", np.std(a))
print("Product:", np.prod(a))
print("Cumulative Sum:", np.cumsum(a))
print("Cumulative Product:", np.cumprod(a))
print("Index of Minimum:", np.argmin(a))
print("Index of Maximum:", np.argmax(a))
print("Absolute Values:", np.abs(a))
print("Unique Values:", np.unique(a))
print("50th Percentile:", np.percentile(a, 50))
print("0.5 Quantile:", np.quantile(a, 0.5))
print("Peak-to-Peak (Range):", np.ptp(a))
print("Any Non-Zero Element:", np.any(a))

Sum: 45
Mean: 5.0
Median: 5.0
Minimum: 1
Maximum: 9
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611
Product: 362880
Cumulative Sum: [ 1  3  6 10 15 21 28 36 45]
Cumulative Product: [     1      2      6     24    120    720   5040  40320 362880]
Index of Minimum: 0
Index of Maximum: 8
Absolute Values: [1 2 3 4 5 6 7 8 9]
Unique Values: [1 2 3 4 5 6 7 8 9]
50th Percentile: 5.0
0.5 Quantile: 5.0
Peak-to-Peak (Range): 8
Any Non-Zero Element: True


#### Handling missing value

In [59]:
# find missing value

arr = np.array([10,20,np.nan,40])
print(arr)
# isnan
print(np.isnan(arr))

# update nan by number
new_arr = np.nan_to_num(arr,nan=100)
print(new_arr)

[10. 20. nan 40.]
[False False  True False]
[ 10.  20. 100.  40.]
