<a href="https://colab.research.google.com/github/DeepandraSingh1225/Aws-ML/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### why np is better

In [2]:
import numpy as np
import time


# python
start = time.time()

sum1 = 0
for i in range(100000):
  sum1 += i*2
end = time.time()

print('for list' , sum1 , end-start)


# numpy

start1 = time.time()

sum2 = 0
arr = np.arange(100000)*2
sum2 = arr.sum()
end1 = time.time()

print('for array' , sum1 , end1-start1)

for list 9999900000 0.036728620529174805
for array 9999900000 0.0011298656463623047


#### zeros

In [20]:
z = np.zeros(2)
print(z)

z = np.zeros((2,2))
z

[0. 0.]
[[0. 0.]
 [0. 0.]]


In [17]:
z = np.zeros((2,2))+7
z

array([[7., 7.],
       [7., 7.]])

#### ones

In [9]:
o = np.ones((2,3))
o

array([[1., 1., 1.],
       [1., 1., 1.]])

#### full

In [10]:
arr = np.full((5),7)
arr

array([7, 7, 7, 7, 7])

In [11]:
arr = np.full((5,5),10)
arr

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [34]:
arr = np.full((4,4,4),7)
arr

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

#### operations for zeros

In [23]:
arr = np.zeros(5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[0. 0. 0. 0. 0.]
(5,)
1
5
float64


In [25]:
arr = np.zeros((5,5))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(5, 5)
2
25
float64


#### operation for ones

In [26]:
arr = np.ones(5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[1. 1. 1. 1. 1.]
(5,)
1
5
float64


In [27]:
arr = np.ones((5,5))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(5, 5)
2
25
float64


#### operation for full

In [28]:
arr = np.full((5),10)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[10 10 10 10 10]
(5,)
1
5
int64


In [32]:
arr = np.full((3,4),10)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
(3, 4)
2
12
int64


- we can not make 2d array using arange so we use reshape

In [56]:
arr = np.arange(6)
print(arr)
print()

arr1 = arr.reshape(2,3)
print(arr1)

[0 1 2 3 4 5]

[[0 1 2]
 [3 4 5]]


#### flatten

In [57]:
arr1 = arr.reshape(2,3)
print(arr1)
print()

arr1.flatten()

[[0 1 2]
 [3 4 5]]



array([0, 1, 2, 3, 4, 5])

#### Ravel

In [58]:
arr = np.arange(6).reshape(2,3)
print(arr)

arr.ravel()

[[0 1 2]
 [3 4 5]]


array([0, 1, 2, 3, 4, 5])

#### flatten vs ravel


In [64]:
print("Flatten")
arr = np.arange(4).reshape(2,2)
print(arr)
print()

arr_new = arr.flatten()
arr_new[0] = 100
print("New :-" , arr_new)
print("Original:-")
print(arr)
print()

print("Ravel")
arr1 = np.arange(4).reshape(2,2)
print(arr1)
print()

arr_new1 = arr1.ravel()
arr_new1[0] = 200
print("New :-" , arr_new1)
print("Original:-")
print( arr1)

Flatten
[[0 1]
 [2 3]]

New :- [100   1   2   3]
Original:-
[[0 1]
 [2 3]]

Ravel
[[0 1]
 [2 3]]

New :- [200   1   2   3]
Original:-
[[200   1]
 [  2   3]]


#### Transpose

In [70]:
arr = np.arange(6).reshape(2,3)
print(arr)
print()

arr1 = arr.T
print(arr1)
print()

print(arr.transpose())

[[0 1 2]
 [3 4 5]]

[[0 3]
 [1 4]
 [2 5]]

[[0 3]
 [1 4]
 [2 5]]
